version: "3.7"

services:
    mysql_app:
        image: mysql:8.1
        container_name: mysql_app
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: phpmyadmin
        ports:
            - 3306:3306
        networks:
            - networks_app

    phpmyadmin_app:
        image: phpmyadmin:5.2
        container_name: phpmyadmin_app
        restart: always
        volumes:
            - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        ports:
            - 8080:80
        networks:
            - networks_app

    wwww_app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: wwww_app
        volumes:
            - ./www:/var/www/html/
            - ./php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql_app
        ports:
          - 8000:80
        networks:
            - networks_app

networks:
    networks_app:
