version: "3.7"
services:
    mysql_sampp:
        image: mysql:8.2
        container_name: mysql_sampp
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ${URL_MYSQL_LIB}:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - network_sampp
    phpmyadmin_sampp:
        image: phpmyadmin:5.2
        container_name: phpmyadmin_sampp
        restart: always
        volumes:
            - ${URL_PHP_CONFIG}:/etc/phpmyadmin/config.user.inc.php
        ports:
            - "${PHPMYADMIN_PORT}:80"
        networks:
            - network_sampp
    wwww_sampp:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: wwww_sampp
        volumes:
            - ${URL_WWW}:/var/www/html/
            - ${URL_PHP_INI}:/usr/local/etc/php/php.ini
        depends_on:
            - mysql_sampp
            - phpmyadmin_sampp
        ports:
            - "${APACHE_PORT}:80"
        networks:
            - network_sampp
networks:
    network_sampp: