version: "3.7"

services:
  httpd_app:
    image: httpd:2.4-alpine
    container_name: httpd_app
    restart: always
    volumes: 
      - ./app:/usr/local/apache2/htdocs
    ports:
      - 8080:80
    networks:
      - networkapp_app
  mysql_app:
    image: mysql:8
    container_name: mysql_app
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_root_password
    ports:
      - 33060:3306
    networks:
      - networkapp_app
networks:
  networkapp_app: